export  const packs = [
    {
        title: "AI BEGINNER",
        description: "Ideal for those new to AI. Get started on your AI journey. Learn the basics of AI algorithms and tools.",
        monthlyPrice: 5.99,
        quarterlyPrice: 4.79, // 20% discount for quarterly
        additionalDetails: {
          monthlyCredits: "💰 100 Credits /month",
          firstMonthCredits: "🤑 150 credits in your first month",
          limitedTimeOffer: "Limited time offer",
          discountedPrice: "$6 $4.79 USD /month* SAVE 20%",
          billedEvery3Months: "$14.37 billed every 3 months",
          quarterlyCreditsDelivery: "Credits delivered quarterly in advance",
          upgradeInfo: "UPGRADE NOW\nCancel any time",
          creditPrice: "$0.048 /credit",
          imageLimit: "310 SDXL images/month^",
          freeFineTune: "1 free fine-tune/month",
          accessModels: "Access PRO-only models",
          communityModels: "Use community fine-tuned models",
          noAds: "No ads",
          creditRollOver: "Credits roll-over & never expire",
          advancedSearch: "Advanced public search",
          privateSearch: "Search your own private creations",
          proBadge: "PRO badge on your profile",
          tipCreators: "Tip other creators",
          earnTopups: "Earn topups and badges as normal",
          pauseCancelInfo: "Pause, delay or cancel any time",
        },
      },
      
      {
        title: "AI HOBBYIST",
        description: "Perfect for AI enthusiasts who want to explore more. Access advanced AI projects and workshops.",
        monthlyPrice: 9.99,
        quarterlyPrice: 7.99, // 20% discount for quarterly
        additionalDetails: {
          monthlyCredits: "💰 200 Credits /month",
          firstMonthCredits: "🤑 300 credits in your first month",
          limitedTimeOffer: "Limited time offer",
          discountedPrice: "$10 $7.99 USD /month* SAVE 20%",
          billedEvery3Months: "$23.97 billed every 3 months",
          quarterlyCreditsDelivery: "Credits delivered quarterly in advance",
          upgradeInfo: "UPGRADE NOW\nCancel any time",
          creditPrice: "$0.04 /credit",
          imageLimit: "410 SDXL images/month^",
          freeFineTune: "1 free fine-tune/month",
          accessModels: "Access PRO-only models",
          communityModels: "Use community fine-tuned models",
          noAds: "No ads",
          creditRollOver: "Credits roll-over & never expire",
          advancedSearch: "Advanced public search",
          privateSearch: "Search your own private creations",
          proBadge: "PRO badge on your profile",
          tipCreators: "Tip other creators",
          earnTopups: "Earn topups and badges as normal",
          pauseCancelInfo: "Pause, delay or cancel any time",
        },
      },
      
      {
        title: "AI ENTHUSIAST",
        description: "For AI enthusiasts who want advanced features and content. Dive deep into AI research and development.",
        monthlyPrice: 9.99,
        quarterlyPrice: 15.99, // 20% discount for quarterly
        additionalDetails: {
          monthlyCredits: "💰 500 Credits /month",
          firstMonthCredits: "🤑 750 credits in your first month",
          limitedTimeOffer: "Limited time offer",
          discountedPrice: "$20 $15.99 USD /month* SAVE 20%",
          billedEvery3Months: "$47.97 billed every 3 months",
          quarterlyCreditsDelivery: "Credits delivered quarterly in advance",
          upgradeInfo: "UPGRADE NOW\nCancel any time",
          creditPrice: "$0.032 /credit",
          imageLimit: "710 SDXL images/month^",
          freeFineTune: "2 free fine-tunes/month",
          accessModels: "Access PRO-only models",
          communityModels: "Use community fine-tuned models",
          noAds: "No ads",
          creditRollOver: "Credits roll-over & never expire",
          advancedSearch: "Advanced public search",
          privateSearch: "Search your own private creations",
          proBadge: "PRO badge on your profile",
          tipCreators: "Tip other creators",
          earnTopups: "Earn topups and badges as normal",
          pauseCancelInfo: "Pause, delay or cancel any time",
        },
      },
      
      {
        title: "AI ARTIST",
        description: "Unlock the full potential of AI for creative projects. Create AI-generated art and music with advanced tools.",
        monthlyPrice: 49.99,
        quarterlyPrice: 39.99, // 20% discount for quarterly
        additionalDetails: {
          monthlyCredits: "💰 1400 Credits /month",
          firstMonthCredits: "🤑 2100 credits in your first month",
          limitedTimeOffer: "Limited time offer",
          discountedPrice: "$50 $39.99 USD /month* SAVE 20%",
          billedEvery3Months: "$119.97 billed every 3 months",
          quarterlyCreditsDelivery: "Credits delivered quarterly in advance",
          upgradeInfo: "UPGRADE NOW\nCancel any time",
          creditPrice: "$0.03 /credit",
          imageLimit: "1,610 SDXL images/month^",
          freeFineTune: "3 free fine-tunes/month",
          accessModels: "Access PRO-only models",
          communityModels: "Use community fine-tuned models",
          noAds: "No ads",
          creditRollOver: "Credits roll-over & never expire",
          advancedSearch: "Advanced public search",
          privateSearch: "Search your own private creations",
          proBadge: "PRO badge on your profile",
          tipCreators: "Tip other creators",
          earnTopups: "Earn topups and badges as normal",
          pauseCancelInfo: "Pause, delay or cancel any time",
        },
      },
      
];