import React from 'react';
import './privacy.css'; // Import your CSS file for styling
//to design further more
const TermsPage: React.FC = () => {
    return (
        <div className="privacy-container">
            <h1 className="privacy-title">Terms Of Service</h1>

            <p className="last-updated">Last updated: 10 December 2023</p>

            <h2>1. Introduction</h2>
            
            <p>Welcome to Imaginify where you can create and purchase artworks generated by Artificial Intelligence (AI) systems (Artwork).
                Our complete terms are contained below, but some important points for you to know before you become a customer are set out below:
                Unless your Membership is suspended or terminated in accordance with these Terms, your Membership will roll over on an ongoing basis;
We may cancel, at any time before delivery and for whatever reason, an order that we have previously accepted. Where we do so, we will refund you using the original payment method used for the order;
We may need to change the Membership Fees from time to time. If we change the Membership Fees, we will provide you with 30 days notice of the change. After 30 days, we will apply the new Membership Fees to your Membership. If you do not agree with the new Membership Fees, you may cancel your Membership in accordance with these terms;
We may terminate your Membership at any time by giving 30 days written notice to you; 
Our liability under these terms is limited to the Price paid by you for the Artworks and/or service the subject of the relevant claim, and we will not be liable for consequential loss;
We will have no liability for loss of, or damage to, the Artworks, any injury or loss to any person, failure or delay in providing the Artworks or a breach of any law, where such loss was caused or contributed to by any event or circumstance beyond our reasonable control or act or omission of you or your related parties;
We may amend these Terms, the features of the Site or your Membership at any time, by providing written notice to you;</p>

            <h2>2. Acceptance and Site Licence</h2>
            <p>You accept these Terms by clicking “I accept” when registering on the Site, placing an order via the Site or using the Site. 
If you are less than 16 years old, you must use the Site with a parent or guardian. </p>

            <h2>3.User Content, Prohibited Conduct and Community Standards</h2>
            <p>You may be permitted to post, upload, publish, submit or transmit relevant information and content (including creating Artworks) (User Content) on the Site.
            When using the Site, you must not do or attempt to do anything that is unlawful or inappropriate, including: 
anything that would constitute a breach of an individual s privacy (including uploading private or personal information without an individual s consent) or any other legal rights;
using the Site to defame, harass, threaten, menace or offend any person;
using the Site for unlawful purposes;
using the Site to submit material or create User Content that is Prohibited Content or infringes on the Community Standards outlined on our Site;
interfering with any user of the Site;
tampering with or modifying the Site (including by transmitting viruses and using trojan horses);
using the Site to send unsolicited electronic messages;
manipulating or misrepresenting community interaction metrics (such as likes) through unauthorised or improper means, including but not limited to alternate account creation or robots; 
using data mining, robots, screen scraping or similar data gathering and extraction tools on the Site; or
facilitating or assisting a third party to do any of the above acts.
Prohibited Content means material or content which is considered to include the following:
content that is abusive, pornographic, deceptive, obscene, slanderous, defamatory, offensive, violent, hate speech or otherwise inappropriate;
content that is homophobic, transphobic, racist or otherwise discriminatory;
content that promotes bullying, personal attacks, harassment or doxing;
content subject to copyright that is used without the express permission of the owner of the content
content that violates or encroaches on the rights of others, including but not limited to Intellectual Property Rights or privacy rights;
content that contains spam, viruses, worms, corrupt files, any corrupt code, Trojan horses or anything else that can cause a security breach and damage;
content that incites, baits or advocates illegal activity or argument or violates any law; or
content that includes non-constructive criticism or creates a hostile or unwelcoming environment; or
content that harms or advocates harm against anyone, including gore.
You agree that you are solely responsible for all User Content that you make available on or through the Site, including on social media using a Tag. You represent and warrant that:
you are either the sole and exclusive owner of all User Content or you have all rights, licences, consents and releases that are necessary to grant to us the rights in such User Content (as contemplated by these Terms);
you will not use the Site to submit material or create User Content that is Prohibited Content; and
neither the User Content nor the posting, uploading, publication, submission or transmission of the User Content or our use of the User Content on, through or by means of our Site (including on social media) will a third party s Intellectual Property Rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation infringe, misappropriate or violate.
            </p>
           

            <h2>4. Moderators and Violations</h2>
           <p>We do not endorse or approve, and are not responsible for, any User Content. We have the right but not the obligation to appoint community moderators or automoderators (Moderators) from time to time to ensure that all User Content meets these Terms.
If you breach or we suspect you may be in breach of these Terms, we or our Moderators may, at any time (at our sole discretion):
delete any User Content;
suspend or terminate your Account (and any associated or linked Accounts), along with all User Content associated with that account;
suspend or permanently ban your access to the Site;</p>

            <h2>5. Accounts</h2>
            <p>
            You may create or purchase Credits from us with an account, which allows you to review your order history, save your Artworks. You may also register for an account using your Gmail or other social media network account (Social Media Account). If you sign in to your account using your Social Media Account, you authorise us to access certain information on your Social Media Account including but not limited to your current profile photo and other basic information.
You must ensure that any personal information you give to us when creating an account is accurate and up-to-date. All personal information that you give to us will be treated in accordance with our Privacy Policy.
It is your responsibility to keep your account details confidential. You are responsible for all activity on your account, including purchases made using your account details.
           </p>

            <h2>6. Imaginify Services</h2>
            <p>We agree to provide you with access to the Site, the support services as detailed in this section, and any other services we agree to provide as set out in your Account, including but not limited to the creation of any Artwork and the purchase of an Artwork.
You may use our Site with or without an Account or Membership to create Artworks or browse and view the Site, however, the number of Artworks you create is limited to your number of Credits. 
We agree to use our best endeavours to make the Site available at all times. However, from time to time we may perform reasonable scheduled and emergency maintenance, and the Site may be unavailable during the times we are performing such maintenance. 
Should you be unable to access the Site, or should you have any other questions or issues impacting on your use and enjoyment of the Site, you must place a request via the Feedback / Support page or by emailing [input email]. We will endeavour to respond to any support requests in a reasonable period. 
Our Site creates Artworks using AI systems. You acknowledge and agree that we do not control or have any input over the final Artwork that is created by you or delivered to you.
We reserve the right to amend, add or remove any AI methods or systems on the Site at our sole discretion.
You acknowledge and agree that the Site may be reliant on, or interface with third party systems that are not provided by us (for example, cloud storage and computing providers and internet providers) (Third Party Services). To the maximum extent permitted by law, we shall have no Liability for any Third Party Services, or any unavailability of the Site due to a failure of the Third Party Services.
You acknowledge and agree that data loss is an unavoidable risk when using any software. To the extent you input any data into the Site, you agree to maintain a backup copy of any data you input into the Site.
To the maximum extent permitted by law, we shall have no Liability to you for any loss or corruption of data, or any scheduled or emergency maintenance that causes the Site to be unavailable. </p>

            <h2>7. Membership</h2>
            <p>
            If you choose to sign up for a Membership, once you have created an Account and chosen a Membership, you agree to pay the membership fee set out on the Site (Membership Fees) by the date specified on the Site (Payment Date) to access certain features (such as additional Credits) on the Site and benefit from your Membership.  
Unless your Membership is suspended or terminated in accordance with these Terms, or you opt to bring the Payment Date forward to access additional Credits, your Membership will roll over on an ongoing monthly basis, and the Membership Fee will be automatically debited on the Payment Date set out on the Site. Without limiting your rights under the Australian Consumer Law, you can cancel your Membership at any time in accordance with the “Cancellation of Memberships” clause of these Terms but the cancellation will only have effect from expiry of the monthly period for which you have paid the Membership Fees.  
You agree that we may set-off or deduct from any monies payable to you under these Terms, any amounts which are payable by you to us (whether under these Terms or otherwise).
Changes to your Membership: If you wish to suspend or change your Membership (for example, by upgrading to a different Membership tier), refer to the Settings section on the Site. 
To the extent permitted by law, the Membership Fees are non-refundable once paid.
We may need to change what is available as part of your Membership (for example, removing certain inclusions, or features) from time to time. If we change what is available as part of your Membership, we will provide you with 30 days notice of the change. After 30 days, we will apply the changes to your Membership. If the changes substantially and adversely affect your enjoyment of the Membership, you may cancel your Membership in accordance with the Cancellation of Memberships clause.
We may need to change the Membership Fees from time to time. If we change the Membership Fees, we will provide you with 30 days notice of the change. After 30 days, we will apply the updated Membership Fee to your Membership. If the updated Membership Fee is not acceptable to you, you may cancel your Membership in accordance with the Cancellation of Memberships clause.   </p>

           <h2>8. Price and payments</h2>
           <p>You must pay us the Membership Fee and/or the purchase price of each physical Artwork you order, plus any applicable delivery costs as set out on the Site (the Price) in accordance with this clause. All amounts are stated in US dollars and any applicable taxes may apply.  
You must pay the Price upfront using one of the methods set out on the Site. 
You must not pay, or attempt to pay, the Price by fraudulent or unlawful means. If you make a payment by debit card or credit card, you warrant that you are authorised to use the debit card or credit card to make the payment.
The payment methods we offer are set out on the Site. We may offer payment through a third-party provider for example, Stripe.com. You acknowledge and agree that we have no control over the actions of the third-party provider, and your use of the third-party payment method is subject to additional terms and conditions as detailed below.
Despite anything to the contrary, our order process is conducted by our online reseller Stripe.com. Stripe.com is the Merchant of Record for all of our orders. Stripe may handle some billing-related customer service enquiries and returns. Your relationship with Stripe is governed by the following Terms and Conditions https://stripe.com/fr-us/legal/ssa and Privacy Policy https://stripe.com/fr-us/privacy as amended from time to time.
We do not store any credit card details, and all payment information is collected and stored through our third-party payment processor.</p>
            <h2>9. Contact Us</h2>
            <p>If you have questions or concerns about our Terms of Service, contact us at:</p>
            <address>
                Imaginify Studio Pty Ltd (ABN 76 654 351 701)<br />
                Email: [insert email]<br />
                Last update: 10 December 2023
            </address>
        </div>
    );
};

export default TermsPage;
