import img1 from '@/public/anime.jpg'
const data =  [
    {
      name: 'Rare Wind',
      description: '#a8edea → #fed6e3',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 200,
      link:'/dashbord',
    },
    {
      name: 'Saint Petersburg',
      description: '#f5f7fa → #c3cfe2',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Deep Blue',
      description: '#e0c3fc → #8ec5fc',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Ripe Malinka',
      description: '#f093fb → #f5576c',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Perfect White',
      description: '#fdfbfb → #ebedee',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Near Moon',
      description: '#5ee7df → #b490ca',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,      
      link:'/dashbord',
    },
    {
      name: 'Wild Apple',
      description: '#d299c2 → #fef9d7',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 200,
      link:'/dashbord',
    },
    {
      name: 'Ladoga Bottom',
      description: '#ebc0fd → #d9ded8',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Sunny Morning',
      description: '#f6d365 → #fda085',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 200,
      link:'/dashbord',
    },
    {
      name: 'Lemon Gate',
      description: '#96fbc4 → #f9f586',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Salt Mountain',
      description: ' #FFFEFF → #D7FFFE',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 200,
      link:'/dashbord',
    },
    {
      name: 'New York',
      description: ' #fff1eb → #ace0f9',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Soft Grass',
      description: ' #c1dfc4 → #deecdd',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 400,
      link:'/dashbord',
    },
    {
      name: 'Japan Blush',
      description: ' #ddd6f3 → #faaca8',
      backgroundImage: `url(${img1.src})`,
      css:'backgroundSize:cover',
      height: 200,
      link:'/dashbord',
    },
  ]
  export default data